
-- ==========================================================
-- Project Name : Hotel Booking Data Engineering Project
-- Platform     : Snowflake
-- Author       : Mahalakshmi Kattamuri
-- Description  : End-to-End ETL pipeline using Snowflake
-- ==========================================================
-- Step 1: Create Warehouse
CREATE OR REPLACE WAREHOUSE HOTEL_WH
WITH
    WAREHOUSE_SIZE ='XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;
    
-- Step 2: Create Database
CREATE OR REPLACE DATABASE HOTEL_BOOKING_DB;

--STEP 3:  Use our database
USE DATABASE HOTEL_BOOKING_DB;

-- Step 4: Create schemas
CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA CURATED;
CREATE OR REPLACE SCHEMA ANALYTICS;

-- ==========================================================
-- RAW LAYER
-- ==========================================================
USE WAREHOUSE HOTEL_WH;
USE DATABASE HOTEL_BOOKING_DB;
USE SCHEMA RAW;

--step 5: creating customer table 
CREATE OR REPLACE TABLE CUSTOMER (
    CUSTOMER_ID INT AUTOINCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PHONE_NUMBER VARCHAR(15),
    DATE_OF_BIRTH DATE,
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(50),
    CREATED_DATE DATE
);
--step 6: creating hotel table
CREATE OR REPLACE TABLE HOTEL (
    HOTEL_ID INT AUTOINCREMENT PRIMARY KEY,
    HOTEL_NAME VARCHAR(100),
    STAR_RATING NUMBER(1),
    HOTEL_ADDRESS VARCHAR(200),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    COUNTRY VARCHAR(50),
    PHONE_NUMBER VARCHAR(15)
);
--STEP 7: creating room table
CREATE OR REPLACE TABLE ROOM (
    ROOM_ID INT AUTOINCREMENT PRIMARY KEY,
    HOTEL_ID INT,
    ROOM_NUMBER VARCHAR(10),
    ROOM_TYPE VARCHAR(30),
    PRICE_PER_NIGHT NUMBER(10,2),
    CAPACITY INT,
    AVAILABILITY_STATUS VARCHAR(20),

    CONSTRAINT FK_ROOM_HOTEL    --it is a contraint building relationship with table to foreingkey
        FOREIGN KEY (HOTEL_ID)
        REFERENCES HOTEL(HOTEL_ID)
);
-- -- Step 8: Create BOOKING table
-- Stores all hotel booking transactions.
-- This is the central transactional table connecting customers and rooms.
CREATE OR REPLACE TABLE BOOKING (
    BOOKING_ID INT AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    ROOM_ID INT,
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    BOOKING_DATE DATE,
    NUMBER_OF_GUESTS INT,
    BOOKING_STATUS VARCHAR(20),

    CONSTRAINT FK_BOOKING_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER(CUSTOMER_ID),

    CONSTRAINT FK_BOOKING_ROOM
        FOREIGN KEY (ROOM_ID)
        REFERENCES ROOM(ROOM_ID)
);
--step 9 creating payment table
CREATE OR REPLACE TABLE PAYMENT (
    PAYMENT_ID INT AUTOINCREMENT PRIMARY KEY,
    BOOKING_ID INT,
    PAYMENT_DATE DATE,
    PAYMENT_MODE VARCHAR(30),
    AMOUNT NUMBER(10,2),
    PAYMENT_STATUS VARCHAR(20),
    TRANSACTION_ID VARCHAR(100),

    CONSTRAINT FK_PAYMENT_BOOKING
        FOREIGN KEY (BOOKING_ID)
        REFERENCES BOOKING(BOOKING_ID)
);

-- Step 10: Create File Format

CREATE OR REPLACE FILE FORMAT CSV_FORMAT...
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

--step 11: creating an internal stage
CREATE OR REPLACE STAGE HOTEL_STAGE
FILE_FORMAT = CSV_FORMAT;
--- LIST @HOTEL_STAGE; --to see all the csv files in stage
--loading data to customer

--Step 12: Load CSV Files into RAW Tables
COPY INTO CUSTOMER
FROM @HOTEL_STAGE/customer.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

--loading data to hotel
COPY INTO HOTEL
FROM @HOTEL_STAGE/hotel.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

--loading data to room
COPY INTO ROOM
FROM @HOTEL_STAGE/rooms.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

--loading data to booking
COPY INTO BOOKING
FROM @HOTEL_STAGE/booking.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

--loading data to payment
COPY INTO PAYMENT
FROM @HOTEL_STAGE/payment.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

-- we dont modify data in raw so we'll use curated schema now creating tables in curated schema

-- ==========================================================
-- CURATED LAYER
-- ==========================================================
USE DATABASE HOTEL_BOOKING_DB;

USE SCHEMA CURATED;

CREATE OR REPLACE TABLE CUSTOMER AS
SELECT
    CUSTOMER_ID,
    INITCAP(TRIM(FIRST_NAME)) AS FIRST_NAME,
    INITCAP(TRIM(LAST_NAME)) AS LAST_NAME,
    LOWER(TRIM(EMAIL)) AS EMAIL,
    PHONE_NUMBER,
    DATE_OF_BIRTH,
    INITCAP(TRIM(CITY)) AS CITY,
    INITCAP(TRIM(STATE)) AS STATE,
    UPPER(TRIM(COUNTRY)) AS COUNTRY,
    CREATED_DATE
FROM RAW.CUSTOMER;

CREATE OR REPLACE TABLE HOTEL AS
SELECT
    HOTEL_ID,
    INITCAP(TRIM(HOTEL_NAME)) AS HOTEL_NAME,
    STAR_RATING,
    INITCAP(TRIM(HOTEL_ADDRESS)) AS HOTEL_ADDRESS,
    INITCAP(TRIM(CITY)) AS CITY,
    INITCAP(TRIM(STATE)) AS STATE,
    UPPER(TRIM(COUNTRY)) AS COUNTRY,
    PHONE_NUMBER
FROM RAW.HOTEL;

CREATE OR REPLACE TABLE ROOM AS
SELECT
    ROOM_ID,
    HOTEL_ID,
    UPPER(TRIM(ROOM_NUMBER)) AS ROOM_NUMBER,
    INITCAP(TRIM(ROOM_TYPE)) AS ROOM_TYPE,
    PRICE_PER_NIGHT,
    CAPACITY,
    UPPER(TRIM(AVAILABILITY_STATUS)) AS AVAILABILITY_STATUS
FROM RAW.ROOM;

CREATE OR REPLACE TABLE BOOKING AS
SELECT
    BOOKING_ID,
    CUSTOMER_ID,
    ROOM_ID,
    CHECK_IN_DATE,
    CHECK_OUT_DATE,
    BOOKING_DATE,
    NUMBER_OF_GUESTS,
    UPPER(TRIM(BOOKING_STATUS)) AS BOOKING_STATUS
FROM RAW.BOOKING;

CREATE OR REPLACE TABLE PAYMENT AS
SELECT
    PAYMENT_ID,
    BOOKING_ID,
    PAYMENT_DATE,
    INITCAP(TRIM(PAYMENT_MODE)) AS PAYMENT_MODE,
    AMOUNT,
    UPPER(TRIM(PAYMENT_STATUS)) AS PAYMENT_STATUS,
    TRANSACTION_ID
FROM RAW.PAYMENT;

-- ===========================================
-- STEP 13: SQL JOINS
-- ===========================================

SELECT
    C.CUSTOMER_ID,
    C.FIRST_NAME,
    C.LAST_NAME,
    B.BOOKING_ID,
    B.CHECK_IN_DATE,
    B.CHECK_OUT_DATE,
    B.BOOKING_STATUS
FROM CUSTOMER C
INNER JOIN BOOKING B
ON C.CUSTOMER_ID = B.CUSTOMER_ID;

SELECT
    C.FIRST_NAME || ' ' || C.LAST_NAME AS CUSTOMER_NAME,
    H.HOTEL_NAME,
    R.ROOM_NUMBER,
    R.ROOM_TYPE,
    B.CHECK_IN_DATE,
    B.CHECK_OUT_DATE,
    P.AMOUNT,
    P.PAYMENT_MODE,
    P.PAYMENT_STATUS
FROM CUSTOMER C
INNER JOIN BOOKING B
    ON C.CUSTOMER_ID = B.CUSTOMER_ID
INNER JOIN ROOM R
    ON B.ROOM_ID = R.ROOM_ID
INNER JOIN HOTEL H
    ON R.HOTEL_ID = H.HOTEL_ID
INNER JOIN PAYMENT P
    ON B.BOOKING_ID = P.BOOKING_ID;

-- ==========================================================
-- ANALYTICS LAYER
-- ==========================================================
USE SCHEMA ANALYTICS;
CREATE OR REPLACE TABLE BOOKING_SUMMARY AS
SELECT
    C.CUSTOMER_ID,
    C.FIRST_NAME || ' ' || C.LAST_NAME AS CUSTOMER_NAME,
    H.HOTEL_NAME,
    R.ROOM_NUMBER,
    R.ROOM_TYPE,
    B.CHECK_IN_DATE,
    B.CHECK_OUT_DATE,
    DATEDIFF('DAY', B.CHECK_IN_DATE, B.CHECK_OUT_DATE) AS TOTAL_DAYS,
    P.AMOUNT,
    P.PAYMENT_MODE,
    P.PAYMENT_STATUS
FROM CURATED.CUSTOMER C
INNER JOIN CURATED.BOOKING B
    ON C.CUSTOMER_ID = B.CUSTOMER_ID
INNER JOIN CURATED.ROOM R
    ON B.ROOM_ID = R.ROOM_ID
INNER JOIN CURATED.HOTEL H
    ON R.HOTEL_ID = H.HOTEL_ID
INNER JOIN CURATED.PAYMENT P
    ON B.BOOKING_ID = P.BOOKING_ID;

-- ===========================================
-- VERIFICATION QUERIES
-- Report 1: Hotel Revenue Summary
-- ===========================================
--Which hotel earned the most revenue?

CREATE OR REPLACE TABLE HOTEL_REVENUE_SUMMARY AS
SELECT
    HOTEL_NAME,
    COUNT(*) AS TOTAL_BOOKINGS,
    SUM(AMOUNT) AS TOTAL_REVENUE,
    AVG(AMOUNT) AS AVERAGE_BOOKING_AMOUNT
FROM BOOKING_SUMMARY
GROUP BY HOTEL_NAME
ORDER BY TOTAL_REVENUE DESC;

-- ===========================================
-- Report 2: Customer spending Summary
-- ===========================================
--Which customer spent the most money?

CREATE OR REPLACE TABLE CUSTOMER_SPENDING_SUMMARY AS
SELECT
    CUSTOMER_NAME,
    COUNT(*) AS TOTAL_BOOKINGS,
    SUM(AMOUNT) AS TOTAL_SPENT,
    AVG(AMOUNT) AS AVERAGE_SPENT
FROM BOOKING_SUMMARY
GROUP BY CUSTOMER_NAME
ORDER BY TOTAL_SPENT DESC;

--Which room type is the most popular and how much revenue does it generate?
CREATE OR REPLACE TABLE ROOM_POPULARITY_SUMMARY AS
SELECT
    ROOM_TYPE,
    COUNT(*) AS TOTAL_BOOKINGS,
    SUM(AMOUNT) AS TOTAL_REVENUE,
    AVG(AMOUNT) AS AVERAGE_REVENUE
FROM BOOKING_SUMMARY
GROUP BY ROOM_TYPE
ORDER BY TOTAL_BOOKINGS DESC, TOTAL_REVENUE DESC;

-- ==========================================================
-- END OF PROJECT
-- ==========================================================
